from __future__ import annotations

APP_SETTING_DEFINITIONS = (
    {
        "key": "WECOM_CORP_ID",
        "label": "企业微信 Corp ID",
        "mode": "editable",
        "input_type": "text",
        "description": "企业微信的唯一标识。",
    },
    {
        "key": "WECOM_AGENT_ID",
        "label": "企业微信 Agent ID",
        "mode": "editable",
        "input_type": "text",
        "description": "企业微信应用的编号。",
    },
    {
        "key": "ADMIN_AUTH_MODE",
        "label": "后台认证模式",
        "mode": "editable",
        "input_type": "text",
        "description": "第一阶段默认 wecom_sso，表示后台主认证使用企业微信 SSO。",
    },
    {
        "key": "ADMIN_LOGIN_REDIRECT_URI",
        "label": "后台登录回调地址",
        "mode": "editable",
        "input_type": "url",
        "description": "企业微信登录完成后回跳的后台地址；为空时按当前域名或可信域名推导。",
    },
    {
        "key": "ADMIN_WECHAT_TRUSTED_DOMAIN",
        "label": "后台可信域名",
        "mode": "editable",
        "input_type": "text",
        "description": "用于拼装企业微信登录回调地址的可信域名，例如 crm.example.com。",
    },
    {
        "key": "WECOM_API_BASE",
        "label": "企业微信接口地址",
        "mode": "editable",
        "input_type": "url",
        "description": "企业微信接口访问地址。",
    },
    {
        "key": "WECOM_DEFAULT_OWNER_USERID",
        "label": "默认负责人账号",
        "mode": "editable",
        "input_type": "text",
        "description": "没有明确负责人时使用的默认负责人账号。",
    },
    {
        "key": "WECOM_PRIVATE_KEY_PATH",
        "label": "会话存档私钥路径",
        "mode": "editable",
        "input_type": "text",
        "description": "会话存档使用的私钥文件路径。",
    },
    {
        "key": "WECOM_SDK_LIB_PATH",
        "label": "会话存档 SDK 路径",
        "mode": "editable",
        "input_type": "text",
        "description": "会话存档 SDK 所在路径。",
    },
    {
        "key": "WECOM_ARCHIVE_TIMEOUT",
        "label": "会话存档超时时间",
        "mode": "editable",
        "input_type": "number",
        "description": "会话存档相关请求的超时时间（秒）。",
    },
    {
        "key": "WECOM_CORP_TAG_LIMIT",
        "label": "企微客户标签上限",
        "mode": "editable",
        "input_type": "number",
        "description": "企微标签管理页面使用的容量提示上限；未配置时默认 1000。",
    },
    {
        "key": "WECHAT_MP_APP_ID",
        "label": "微信公众号 App ID",
        "mode": "editable",
        "input_type": "text",
        "description": "微信授权所使用的公众号 App ID。",
    },
    {
        "key": "WECHAT_MP_OAUTH_SCOPE",
        "label": "微信授权范围",
        "mode": "editable",
        "input_type": "text",
        "description": "微信授权时使用的范围设置。",
    },
    {
        "key": "WECHAT_PAY_ENABLED",
        "label": "微信支付已启用",
        "mode": "editable",
        "input_type": "text",
        "description": "填写 true / false 或 1 / 0。开启后微信内 H5 JSAPI 支付接口才允许下单。",
    },
    {
        "key": "WECHAT_PAY_APP_ID",
        "label": "微信支付 AppID",
        "mode": "editable",
        "input_type": "text",
        "description": "JSAPI 支付使用的公众号 AppID；为空时复用 WECHAT_MP_APP_ID。",
    },
    {
        "key": "WECHAT_PAY_APP_SECRET",
        "label": "微信支付 App Secret",
        "mode": "masked",
        "input_type": "password",
        "description": "JSAPI 支付 AppID 对应的 OAuth 密钥；为空时仅在共用公众号 AppID 时复用 WECHAT_MP_APP_SECRET。",
    },
    {
        "key": "WECHAT_PAY_MCH_ID",
        "label": "微信支付商户号",
        "mode": "editable",
        "input_type": "text",
        "description": "微信支付商户平台分配的商户号 mchid。",
    },
    {
        "key": "WECHAT_PAY_PRIVATE_KEY_PATH",
        "label": "微信支付商户私钥路径",
        "mode": "editable",
        "input_type": "text",
        "description": "APIv3 请求签名使用的商户 API 证书私钥 PEM 文件路径。",
    },
    {
        "key": "WECHAT_PAY_PLATFORM_PUBLIC_KEY_PATH",
        "label": "微信支付平台证书/公钥路径",
        "mode": "editable",
        "input_type": "text",
        "description": "支付通知验签使用的微信支付平台证书 PEM 或平台公钥 PEM 文件路径。",
    },
    {
        "key": "WECHAT_PAY_PLATFORM_CERT_SERIAL_NO",
        "label": "微信支付平台证书序列号",
        "mode": "editable",
        "input_type": "text",
        "description": "支付通知请求头 Wechatpay-Serial 的期望序列号；为空时只用证书/公钥验签。",
    },
    {
        "key": "WECHAT_PAY_NOTIFY_URL",
        "label": "微信支付通知地址",
        "mode": "editable",
        "input_type": "url",
        "description": "微信支付异步通知 URL，例如 https://www.youcangogogo.com/api/h5/wechat-pay/notify。",
    },
    {
        "key": "WECHAT_PAY_API_BASE",
        "label": "微信支付 API Base",
        "mode": "editable",
        "input_type": "url",
        "description": "默认 https://api.mch.weixin.qq.com。",
    },
    {
        "key": "WECHAT_PAY_TIMEOUT_SECONDS",
        "label": "微信支付请求超时",
        "mode": "editable",
        "input_type": "number",
        "description": "调用微信支付 API 的超时时间（秒）。",
    },
    {
        "key": "WECHAT_PAY_PRODUCT_CATALOG_JSON",
        "label": "微信支付商品目录",
        "mode": "editable",
        "input_type": "textarea",
        "description": "服务端商品白名单 JSON；每个商品需配置 product_code、name、description、amount_total。",
    },
    {
        "key": "WECHAT_PAY_API_V3_KEY",
        "label": "微信支付 APIv3 密钥",
        "mode": "masked",
        "input_type": "password",
        "description": "32 字节 APIv3 密钥，用于回调报文解密。页面不会显示完整内容；留空表示保持原值。",
    },
    {
        "key": "WECHAT_PAY_CERT_SERIAL_NO",
        "label": "微信支付商户证书序列号",
        "mode": "masked",
        "input_type": "password",
        "description": "商户 API 证书序列号，用于请求签名 Authorization。页面不会显示完整内容；留空表示保持原值。",
    },
    {
        "key": "WECOM_SECRET",
        "label": "企业微信 Secret",
        "mode": "masked",
        "input_type": "password",
        "description": "企业微信主应用密钥。页面不会显示完整内容；留空表示保持原值。",
    },
    {
        "key": "WECOM_CONTACT_SECRET",
        "label": "企业微信联系人 Secret",
        "mode": "masked",
        "input_type": "password",
        "description": "企业微信联系人接口密钥。页面不会显示完整内容；留空表示保持原值。",
    },
    {
        "key": "WECOM_ARCHIVE_SECRET",
        "label": "会话存档 Secret",
        "mode": "masked",
        "input_type": "password",
        "description": "会话存档接口密钥。页面不会显示完整内容；留空表示保持原值。",
    },
    {
        "key": "WECOM_CALLBACK_TOKEN",
        "label": "回调 Token",
        "mode": "masked",
        "input_type": "password",
        "description": "回调验证令牌。页面不会显示完整内容；留空表示保持原值。",
    },
    {
        "key": "WECOM_CALLBACK_AES_KEY",
        "label": "回调 AES Key",
        "mode": "masked",
        "input_type": "password",
        "description": "回调加密密钥。页面不会显示完整内容；留空表示保持原值。",
    },
    {
        "key": "WECHAT_MP_APP_SECRET",
        "label": "微信公众号 App Secret",
        "mode": "masked",
        "input_type": "password",
        "description": "微信授权密钥。页面不会显示完整内容；留空表示保持原值。",
    },
    {
        "key": "AICRM_AUTH_ISSUER",
        "label": "统一授权平台 Issuer",
        "mode": "editable",
        "input_type": "url",
        "description": "私有化部署的 JWT issuer，例如 https://crm.example.com/oauth。",
    },
    {
        "key": "AICRM_AUTH_SESSION_HASH_PEPPER",
        "label": "会话凭据哈希 Pepper",
        "mode": "masked",
        "input_type": "password",
        "description": "服务端会话和 CSRF 凭据的哈希 pepper；必须通过 Secret Store 管理。",
    },
    {
        "key": "AICRM_AUTH_JWT_SIGNING_KEY",
        "label": "机器访问 JWT 签名密钥",
        "mode": "masked",
        "input_type": "password",
        "description": "单租户私有化环境的 HS256 签名密钥；必须通过 Secret Store 管理。",
    },
    {
        "key": "AICRM_AUTH_TRUSTED_PROXY_ADDRESSES",
        "label": "授权平台可信代理地址",
        "mode": "editable",
        "input_type": "text",
        "description": "可信反向代理 IP/CIDR 列表，仅用于安全解析真实来源 IP。",
    },
    {
        "key": "AICRM_AUTH_CA_FILE",
        "label": "授权平台 CA 路径",
        "mode": "editable",
        "input_type": "text",
        "description": "内部 OAuth HTTPS 服务端证书 CA 文件绝对路径。",
    },
    *(
        {
            "key": key,
            "label": label,
            "mode": "editable",
            "input_type": "text",
            "description": "由授权平台注册并分配的用途级机器身份 client_id。",
        }
        for key, label in (
            ("AICRM_AUTH_AUTOMATION_WORKER_CLIENT_ID", "自动化 Worker Client ID"),
            ("AICRM_AUTH_ARCHIVE_WORKER_CLIENT_ID", "消息归档 Worker Client ID"),
            ("AICRM_AUTH_CALLBACK_WORKER_CLIENT_ID", "回调 Worker Client ID"),
            ("AICRM_AUTH_GROUP_BROADCAST_CLIENT_ID", "群发 Worker Client ID"),
            ("AICRM_AUTH_IDENTITY_CLIENT_ID", "身份解析 Client ID"),
            ("AICRM_AUTH_MCP_CLIENT_ID", "MCP Client ID"),
            ("AICRM_AUTH_EXTERNAL_AGENT_CLIENT_ID", "外部 Agent Client ID"),
            ("AICRM_AUTH_CAMPAIGN_AGENT_CLIENT_ID", "Campaign Agent Client ID"),
            ("AICRM_AUTH_OPS_REPORTER_CLIENT_ID", "运营闭环上报 Client ID"),
            ("AICRM_AUTH_OPERATION_RUNNER_CLIENT_ID", "本地运营执行器 Client ID"),
        )
    ),
    *(
        {
            "key": key.removesuffix("_CLIENT_ID") + "_CLIENT_SECRET_REF",
            "label": label.replace("Client ID", "Client Secret 引用"),
            "mode": "editable",
            "input_type": "text",
            "description": "由引导脚本写入 Secret Store 后生成的 secretref；不得填写明文密钥。",
        }
        for key, label in (
            ("AICRM_AUTH_AUTOMATION_WORKER_CLIENT_ID", "自动化 Worker Client ID"),
            ("AICRM_AUTH_ARCHIVE_WORKER_CLIENT_ID", "消息归档 Worker Client ID"),
            ("AICRM_AUTH_CALLBACK_WORKER_CLIENT_ID", "回调 Worker Client ID"),
            ("AICRM_AUTH_GROUP_BROADCAST_CLIENT_ID", "群发 Worker Client ID"),
            ("AICRM_AUTH_IDENTITY_CLIENT_ID", "身份解析 Client ID"),
            ("AICRM_AUTH_MCP_CLIENT_ID", "MCP Client ID"),
            ("AICRM_AUTH_EXTERNAL_AGENT_CLIENT_ID", "外部 Agent Client ID"),
            ("AICRM_AUTH_CAMPAIGN_AGENT_CLIENT_ID", "Campaign Agent Client ID"),
            ("AICRM_AUTH_OPS_REPORTER_CLIENT_ID", "运营闭环上报 Client ID"),
            ("AICRM_AUTH_OPERATION_RUNNER_CLIENT_ID", "本地运营执行器 Client ID"),
        )
    ),
    {
        "key": "AICRM_AUTH_OUTBOUND_WEBHOOK_CLIENT_ID",
        "label": "出站 Webhook Client ID",
        "mode": "editable",
        "input_type": "text",
        "description": "External Effect 出站 Webhook 使用的已注册 HMAC client_id。",
    },
    {
        "key": "OPENCLAW_WEBHOOK_URL",
        "label": "OpenClaw Webhook 地址",
        "mode": "editable",
        "input_type": "url",
        "description": "一键自动化写话术推送到 OpenClaw 的 webhook 地址。",
    },
    {
        "key": "OPENCLAW_FOCUS_MESSAGE_WEBHOOK_TIMEOUT_SECONDS",
        "label": "重点跟进消息 Webhook 超时",
        "mode": "editable",
        "input_type": "number",
        "description": "重点跟进消息 webhook 请求超时时间（秒）。",
    },
    {
        "key": "DEEPSEEK_ENABLED",
        "label": "DeepSeek 已启用",
        "mode": "editable",
        "input_type": "text",
        "description": "填写 true / false 或 1 / 0。控制 CRM 内部 DeepSeek 调用是否启用。",
    },
    {
        "key": "DEEPSEEK_API_KEY",
        "label": "DeepSeek API Key",
        "mode": "masked",
        "input_type": "password",
        "description": "DeepSeek API Key。页面不会显示完整内容；留空表示保持原值。",
    },
    {
        "key": "DEEPSEEK_BASE_URL",
        "label": "DeepSeek Base URL",
        "mode": "editable",
        "input_type": "url",
        "description": "DeepSeek 接口基础地址。",
    },
    {
        "key": "DEEPSEEK_ROUTER_MODEL",
        "label": "DeepSeek Router Model",
        "mode": "editable",
        "input_type": "text",
        "description": "中央路由 Agent 默认使用的模型名。",
    },
    {
        "key": "DEEPSEEK_EXECUTION_MODEL",
        "label": "DeepSeek Execution Model",
        "mode": "editable",
        "input_type": "text",
        "description": "执行 Agent 默认使用的模型名。",
    },
    {
        "key": "DEEPSEEK_REASONER_MODEL",
        "label": "DeepSeek Reasoner Model",
        "mode": "editable",
        "input_type": "text",
        "description": "需要更强推理时显式切换使用的模型名，默认 deepseek-reasoner。",
    },
    {
        "key": "DEEPSEEK_TIMEOUT_SECONDS",
        "label": "DeepSeek 超时时间",
        "mode": "editable",
        "input_type": "number",
        "description": "DeepSeek 请求超时时间（秒）。",
    },
    {
        "key": "OUTBOUND_WEBHOOK_RETRY_ENABLED",
        "label": "启用出站 Webhook 自动重试",
        "mode": "editable",
        "input_type": "text",
        "description": "填写 true / false 或 1 / 0。只影响 OpenClaw 焦点消息 webhook 和问卷提交外发 webhook。",
    },
    {
        "key": "OUTBOUND_WEBHOOK_RETRY_MAX_ATTEMPTS",
        "label": "出站 Webhook 最大重试次数",
        "mode": "editable",
        "input_type": "number",
        "description": "出站 webhook 首次失败后的最大尝试次数，默认 3。",
    },
    {
        "key": "OUTBOUND_WEBHOOK_RETRY_INTERVAL_SECONDS",
        "label": "出站 Webhook 重试间隔（秒）",
        "mode": "editable",
        "input_type": "number",
        "description": "出站 webhook 失败后进入 retry_scheduled 的间隔秒数，默认 60。",
    },
    {
        "key": "QUESTIONNAIRE_SUBMIT_WEBHOOK_URL",
        "label": "问卷提交外发 Webhook 地址",
        "mode": "editable",
        "input_type": "url",
        "description": "问卷提交成功后，按固定格式外发 mobile / userid / unionid 的 webhook 地址。",
    },
    {
        "key": "QUESTIONNAIRE_SUBMIT_WEBHOOK_TIMEOUT_SECONDS",
        "label": "问卷提交 Webhook 超时",
        "mode": "editable",
        "input_type": "number",
        "description": "问卷提交外发 webhook 请求超时时间（秒）。",
    },
    {
        "key": "QUESTIONNAIRE_EXTERNAL_PUSH_GLOBAL_ENABLED",
        "label": "问卷外推全局总开关",
        "mode": "editable",
        "input_type": "text",
        "description": "填写 true / false 或 1 / 0。关闭后，已开启问卷外推的问卷提交会直接记录“全局关闭跳过”，不再发起外推请求。",
    },
    {
        "key": "QUESTIONNAIRE_EXTERNAL_PUSH_TIMEOUT_SECONDS",
        "label": "问卷外推请求超时",
        "mode": "editable",
        "input_type": "number",
        "description": "问卷外推请求超时时间（秒），默认 3，最大按 10 秒截断。",
    },
)
